from __future__ import annotations

from typing import Protocol

from PIL import Image

from src.platform.models import Rect


class WindowGateway(Protocol):
    def enumerate_windows(self) -> tuple[int, ...]: ...

    def is_window(self, handle: int) -> bool: ...

    def is_window_visible(self, handle: int) -> bool: ...

    def get_foreground_window(self) -> int: ...

    def focus_window(self, handle: int) -> None: ...

    def get_window_text(self, handle: int) -> str: ...

    def get_class_name(self, handle: int) -> str: ...

    def get_window_rect(self, handle: int) -> Rect: ...

    def get_client_rect(self, handle: int) -> Rect: ...

    def capture_rect(self, rect: Rect) -> Image.Image: ...